### ISSUE TITLE
Support for Spanish wikipedia

### ISSUE THREAD

**Issue by jamesmaa** [MarvNC/wikipedia-yomitan#10]
How much work would it take?

**Comment by MarvNC** [comment]
I don't know anything about spanish - is there ruby text involved? If not it should be trivial, I'll try to add all the other languages in DBpedia while I'm at it.
![msedge_Main_2024-07-10_23-43-40](https://github.com/MarvNC/wikipedia-yomitan/assets/17340496/b118f421-9067-4e7a-867d-8aded63f2131)

**Comment by MarvNC** [comment]
Resolved: https://github.com/MarvNC/wikipedia-yomitan/releases/tag/v1.6.1
